
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello, world!
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.6
      CodeUri: ./
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
  LambdaInvokePermission: 
    Type: "AWS::Lambda::Permission"
    Properties: 
      FunctionName: 
        Fn::GetAtt: 
          - "HelloWorldFunction"
          - "Arn"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: "arn:aws:execute-api:us-west-2:158233330829:4yciq5ezb0/Prod/ANY/"
