
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello, world!
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.6
      CodeUri: ./
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
  LambdaInvokePermission: 
    Type: "AWS::Lambda::Permission"
    Properties: 
      FunctionName: arn:aws:lambda:us-west-2:158233330829:function:BetaStack-HelloWorldFunction-LNQ1ATL8KGK6
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceAccount: 
        Ref: "AWS::AccountId"
